name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      # https://github.com/actions/runner-images
      matrix:
        include:
          - os: ubuntu-22.04
            java: 8
            distribution: zulu
          - os: ubuntu-24.04
            java: 8
            distribution: zulu
          - os: ubuntu-22.04
            java: 17
            distribution: temurin
          - os: macos-14
            java: 8
            distribution: zulu
          - os: macos-13
            java: 8
            distribution: zulu
          - os: macos-12
            java: 8
            distribution: zulu
          - os: windows-2022
            java: 8
            distribution: zulu
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup sbt
      uses: eed3si9n/setup-sbt@9b4404aac5da5df5f182eedb3a4083ad9a5d113e
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - name: Build and test
      shell: bash
      run: sbt -v +test
