name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      # https://github.com/actions/runner-images
      matrix:
        include:
          - os: ubuntu-22.04
            java: 8
            distribution: zulu
          - os: ubuntu-24.04
            java: 8
            distribution: zulu
          - os: ubuntu-22.04
            java: 17
            distribution: temurin
          - os: macos-14
            java: 8
            distribution: zulu
          - os: macos-13
            java: 8
            distribution: zulu
          - os: macos-12
            java: 8
            distribution: zulu
          - os: windows-2022
            java: 8
            distribution: zulu
    runs-on: ${{ matrix.os }}
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.9.9
    - name: Build and test
      shell: bash
      run: sbt -v +test
